"""
Django settings for ai_solution project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p79&t=$h5qjb(pr#8s6!!+(_7xo1+4i4n7blko9m)*j^#wtd3('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ai_solution.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_solution.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'main' / 'static',
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/accounts/login/'

ASGI_APPLICATION = 'ai_solution.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

JAZZMIN_SETTINGS = {
    "site_title": "AI Solution Admin",
    "site_header": "AI Solution",
    "site_brand": "AI Solution",
    "welcome_sign": "Welcome to AI Solution Admin",
    "copyright": "AI Solution Ltd",
    "search_model": ["main.ContactMessage", "main.BlogPost", "main.Service"],
    
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin-dashboard", "permissions": ["auth.view_user"]},
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"app": "main"},
    ],
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.contactmessage": "fas fa-envelope",
        "main.service": "fas fa-cogs",
        "main.blogpost": "fas fa-blog",
        "main.event": "fas fa-calendar",
        "main.testimonial": "fas fa-quote-right",
        "main.teammember": "fas fa-users",
        "main.gallery": "fas fa-images",
        "main.portfolio": "fas fa-briefcase",
        "main.faq": "fas fa-question-circle",
        "main.newsletter": "fas fa-newspaper",
        "main.technology": "fas fa-microchip",
        "dashboard": "fas fa-tachometer-alt",
        "analytics": "fas fa-chart-line",
    },
    
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    ############
    # Dashboard #
    ############
    "dashboard_widgets": [
        "auth_users",
        "recent_actions",
        {
            "model": "main.ContactMessage",
            "name": "Recent Messages",
            "limit": 5,
            "chart_type": "line",
        },
        {
            "model": "main.BlogPost",
            "name": "Blog Statistics",
            "limit": 5,
            "chart_type": "bar",
        },
        {
            "model": "main.Service",
            "name": "Services Overview",
            "limit": 5,
            "chart_type": "pie",
        },
    ],
    "dashboard_charts": [
        {
            "title": "Monthly Messages",
            "chart_type": "line",
            "model": "main.ContactMessage",
            "group_by": "created_at",
            "date_field": "created_at",
            "filter_by": {"created_at__year": "2024"},
        },
    ],

    # Add these settings for dashboard integration
    "custom_links": {
        "main": [{
            "name": "Analytics Dashboard", 
            "url": "admin-dashboard", 
            "icon": "fas fa-chart-line",
            "permissions": ["auth.view_user"]
        }]
    },

    "order_with_respect_to": ["auth", "main"],
    
    # Modify the default index (dashboard) to your custom one
    "default_site_index": "admin-dashboard",
    
    # Show charts on the index page
    "show_chart_index": True,

    # Custom CSS for charts
    "custom_css": None,
    "custom_js": None,

    # Show charts on the index page
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-primary",
    "no_navbar_border": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Or your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'  # Use app password for Gmail
